spring:
  kafka:
    consumer:
        group-id: tpd-loggers
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#        properties: spring.json.trusted.package=*
 
    bootstrap-servers: 192.168.0.107:9092      
tpd:
    topic-name: northyork
    message-per-request: 10
    

